name: Mirror Repo

on: workflow_dispatch

jobs:
  mirror:
    name: Mirror Repo
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: yesolutions/mirror-action@v0.7.0
#        with:
#          REMOTE: 'git@github.com:sjohnr/mirror-test-2.git'
#          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
#          GIT_SSH_PUBLIC_KEY: ${{ secrets.GIT_SSH_PUBLIC_KEY }}
#          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
      - uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
        with:
          source-repo: "git@github.com:sjohnr/mirror-test-1.git"
          destination-repo: "git@github.com:sjohnr/mirror-test-2.git"

